SPRING_PROFILES_ACTIVE=railway
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=MIUKImMxQqysHVQYdviUezQdrjBUjfwD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Disable Redis, use no-op cache instead
spring.cache.type=none
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration