spring.application.name=payflow

spring.datasource.url=jdbc:postgresql://localhost:5432/payflowdb
spring.datasource.username=postgres
spring.datasource.password=admin1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
app.jwt.secret=${JWT_SECRET:payflow-dev-secret-key-change-this-in-production-min-32-chars}
app.jwt.expiration-ms=${JWT_EXPIRY_MS:3600000}